-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 10:03:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema consultorio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema consultorio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consultorio` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `consultorio` ;

-- -----------------------------------------------------
-- Table `consultorio`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`consulta` (
  `id_consulta` INT(11) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_paciente` INT(11) NOT NULL,
  `id_profesional` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `id_tconsulta` INT NOT NULL,
  PRIMARY KEY (`id_consulta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`localidad` (
  `id_localidad` INT(10) UNSIGNED NOT NULL,
  `id_provincia` TINYINT(3) UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `codigopostal` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`provincia` (
  `id_provincia` TINYINT(3) UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `codigo31662` CHAR(4) NOT NULL,
  PRIMARY KEY (`id_provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`domicilio` (
  `id_domicilio` INT(11) NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `nro` INT(11) NULL DEFAULT NULL,
  `cruce1` VARCHAR(100) NULL DEFAULT NULL,
  `cruce2` VARCHAR(100) NULL DEFAULT NULL,
  `piso` INT(11) NULL DEFAULT NULL,
  `dpto` VARCHAR(5) NULL DEFAULT NULL,
  `codigopostal` SMALLINT(6) NOT NULL,
  `id_localidad` INT(10) UNSIGNED NOT NULL,
  `id_provincia` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_domicilio`),
  INDEX `domicilio-localidad_idx` (`id_localidad` ASC),
  INDEX `domicilio-provincia_idx` (`id_provincia` ASC),
  CONSTRAINT `domicilio-localidad`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `consultorio`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `domicilio-provincia`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `consultorio`.`provincia` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`tcontacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`tcontacto` (
  `id_tcontacto` INT(11) NOT NULL,
  `descripcion` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tcontacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`libreta_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`libreta_contacto` (
  `id_lcontacto` INT(11) NOT NULL,
  `id_tcontacto` INT(11) NOT NULL,
  `id_domicilio` INT(11) NOT NULL,
  `contacto` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_lcontacto`),
  INDEX `libreta-contacto_idx` (`id_tcontacto` ASC),
  INDEX `libreta-domicilio_idx` (`id_domicilio` ASC),
  CONSTRAINT `libreta-contacto`
    FOREIGN KEY (`id_tcontacto`)
    REFERENCES `consultorio`.`tcontacto` (`id_tcontacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `libreta-domicilio`
    FOREIGN KEY (`id_domicilio`)
    REFERENCES `consultorio`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`obra_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`obra_social` (
  `id_obsoc` INT(11) NOT NULL,
  `obra_social` VARCHAR(100) NULL DEFAULT NULL,
  `diferenciado` DOUBLE NOT NULL,
  PRIMARY KEY (`id_obsoc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`paciente` (
  `id_paciente` INT(11) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `dni` INT(8) NOT NULL,
  `fnac` DATETIME NOT NULL,
  `id_domicilio` INT(11) NOT NULL,
  `id_obsoc` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_paciente`),
  INDEX `paciente-obrasocial_idx` (`id_obsoc` ASC),
  INDEX `paciente-domicilio_idx` (`id_domicilio` ASC),
  CONSTRAINT `paciente-consulta`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `consultorio`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paciente-obrasocial`
    FOREIGN KEY (`id_obsoc`)
    REFERENCES `consultorio`.`obra_social` (`id_obsoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `paciente-domicilio`
    FOREIGN KEY (`id_domicilio`)
    REFERENCES `consultorio`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`profesional` (
  `id_profesional` INT(11) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` INT(8) NOT NULL,
  `id_domicilio` INT(11) NOT NULL,
  `id_especialidad` INT(11) NOT NULL,
  PRIMARY KEY (`id_profesional`),
  INDEX `profesional-domicilio_idx` (`id_domicilio` ASC),
  CONSTRAINT `profesional-consulta`
    FOREIGN KEY (`id_profesional`)
    REFERENCES `consultorio`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `profesional-domicilio`
    FOREIGN KEY (`id_domicilio`)
    REFERENCES `consultorio`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`tipo_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`tipo_consulta` (
  `id_tconsulta` INT(11) NOT NULL,
  `tipo_consulta` VARCHAR(45) NOT NULL,
  `arancel` DOUBLE NOT NULL,
  PRIMARY KEY (`id_tconsulta`),
  CONSTRAINT `tipo-consulta`
    FOREIGN KEY (`id_tconsulta`)
    REFERENCES `consultorio`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`usuario` (
  `id_usuario` INT(11) NOT NULL,
  `user` VARCHAR(8) NOT NULL,
  `pass` VARCHAR(8) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `dni` INT(8) NOT NULL,
  `fnac` DATETIME NOT NULL,
  `id_domicilio` INT(11) NOT NULL,
  `id_obsoc` INT(11) NULL DEFAULT NULL,
  `domicilio_id_domicilio` INT(11) NOT NULL,
  `consulta_id_consulta` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`, `domicilio_id_domicilio`, `consulta_id_consulta`),
  INDEX `usuario-domicilio_idx` (`id_domicilio` ASC),
  INDEX `fk_usuario_consulta1_idx` (`consulta_id_consulta` ASC),
  CONSTRAINT `usuario-domicilio`
    FOREIGN KEY (`id_domicilio`)
    REFERENCES `consultorio`.`domicilio` (`id_domicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_consulta1`
    FOREIGN KEY (`consulta_id_consulta`)
    REFERENCES `consultorio`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`Profesional_obsocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`Profesional_obsocial` (
  `id_profesional` INT(11) NOT NULL,
  `id_obsoc` INT(11) NOT NULL,
  PRIMARY KEY (`id_profesional`, `id_obsoc`),
  INDEX `fk_profesional_has_obra_social_obra_social1_idx` (`id_obsoc` ASC),
  INDEX `fk_profesional_has_obra_social_profesional1_idx` (`id_profesional` ASC),
  CONSTRAINT `fk_profesional_has_obra_social_profesional1`
    FOREIGN KEY (`id_profesional`)
    REFERENCES `consultorio`.`profesional` (`id_profesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesional_has_obra_social_obra_social1`
    FOREIGN KEY (`id_obsoc`)
    REFERENCES `consultorio`.`obra_social` (`id_obsoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `consultorio`.`periodo_no_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`periodo_no_laboral` (
  `id_pnlaboral` INT NOT NULL,
  `id_profesional` INT NOT NULL,
  `desde` DATE NOT NULL,
  `hasta` DATE NOT NULL,
  PRIMARY KEY (`id_pnlaboral`),
  INDEX `pnl-profesional_idx` (`id_profesional` ASC),
  CONSTRAINT `pnl-profesional`
    FOREIGN KEY (`id_profesional`)
    REFERENCES `consultorio`.`profesional` (`id_profesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consultorio`.`dias_no_laborables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consultorio`.`dias_no_laborables` (
  `id_dnlaborable` INT NOT NULL,
  `dia_no_laborable` DATE NOT NULL,
  PRIMARY KEY (`id_dnlaborable`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
